datalayer/jupyter-ui

package.json, src/components/notebook/Notebook.tsx, src/components/notebook/NotebookAdapter.ts, src/components/notebook/render/marked.ts
Fixes https://github.com/datalayer/jupyter-react/issues/14
Before
After
=> Ensure cell markdown output are correctly formatted

packages/react/src/components/notebook/Notebook.css, packages/react/src/components/notebook/Notebook.tsx, packages/react/src/example/JupyterExample.tsx, packages/react/style/index.css
Changes :
Jupyter-react Notebook CSS fixed
To use :
Provide a container around Notebook component with specified height and width.
The Notebook component by jupyter-react will size itself according to the container.
E.g
`
<div style={{height:"100vh", width:"100vw"}}>
<Notebook />
</div>
`
=> Fixed CSS for Notebook

packages/react/src/components/notebook/cell/sidebar/CellSidebarNew.tsx, packages/react/src/examples/toolbars/NotebookToolbar.tsx, packages/react/src/examples/toolbars/NotebookToolbarAutoSave.tsx
This PR contains the migration of MUI to primer for the directory /packages/react.
=> Convert MUI to Primer for /packages/react

docs/docs/deployments/amplify/_category_.yml, docs/docs/deployments/amplify/index.mdx
Since I noticed that you upload the images to the S3 bucket, I have attached the images here for convenience. Please upload them to the bucket and use the respective image links in the documentation. Apologies for any inconvenience caused. Thank you in advance!
image-0: 
image-1: 
image-2:
image-3
=> feat: Create index.mdx with Amplify setup instructions under deployments docs

docs/docs/deployments/amplify/index.mdx
It seems the indentation was wrong. PR to fix it.
=> Fix: indentation in deployment docs (amplify)

docs/docs/develop/setup/devcontainers.mdx
Adding additional info in case other people are stuck at the same steps I am
=> README - Update build step

packages/react/package.json
Removing the emoji in the description of jupyter-ui react fixes the issue.
Fixes #119
=> Fix CI on Windows

packages/react/package.json, packages/react/src/jupyter/Jupyter.tsx, packages/react/src/jupyter/theme.ts
Set design tokens of primer react with the one of JupyterLab to more homogeneous look and feel.
Fixes partly #115; some design tokens were not assigned and will certainly require follow-up work.
=> First iteration to sync primer react with JupyterLab theme

.github/workflows/publish-dev.yml
Fix yarn 3 availability in publication workflow
=> fix: enable yarn 3

.vscode/settings.json, docs/docs/components/StorybookView.js, docs/docs/components/cell/index.mdx, docs/docs/components/console/index.mdx, docs/docs/components/notebook/index.mdx, docs/docs/develop/develop/index.mdx, packages/react/webpack.lab-config.js
Set up docusaurus to display stories for documentation
Add webpack config requirements for packaging Pyodide kernel
=> Use docusaurus as doc source

packages/react/.storybook/preview.ts, packages/react/src/components/cell/Cell.tsx, packages/react/src/components/console/Console.tsx, packages/react/src/components/console/ConsoleAdapter.ts, packages/react/src/components/terminal/Terminal.tsx, packages/react/src/components/terminal/TerminalAdapter.ts, packages/react/src/examples/Console.tsx, packages/react/src/examples/ConsoleLite.tsx, packages/react/src/jupyter/Jupyter.tsx, packages/react/src/jupyter/JupyterContext.tsx, packages/react/stories/Cell.stories.tsx, packages/react/stories/Console.stories.tsx, packages/react/stories/Notebook.stories.tsx, packages/react/stories/Notebook.test.ts, packages/react/stories/Terminal.stories.tsx
- Add initCode to `Jupyter` and `JupyterContext` to initialize the default kernel
- Add initCode to `Terminal`
- Switch `Console.code` from `string[]` to `string`
Fixes #178
=> Add initCode

packages/react/package.json, packages/react/src/jupyter/kernel/KernelExecutor.ts
It also bump @primer/react (needed elsewhere).
=> Fix default kernel execution options

examples/next-js/src/app/page.tsx, examples/next-js/src/components/CellComponent.tsx, examples/next-js/src/components/NotebookComponent.tsx, packages/react/src/examples/NotebookThemeColorMode.tsx, packages/react/src/jupyter/lab/JupyterLabCss.tsx, packages/react/src/typings.d.ts, packages/react/webpack.config.js
Fixes #104
[Screencast from 05-07-2024 04:10:55 PM.webm](https://github.com/datalayer/jupyter-ui/assets/226720/8c438cd0-46a9-41c7-b558-b8a951626ca3)
=> Next-js theme and color mode

README.md, examples/cra/package.json, examples/next-js/next.config.js, examples/next-js/package.json, packages/react/.storybook/manager.ts, packages/react/package.json, packages/react/src/jupyter/ipywidgets/libembed-amd.ts
Fixes https://github.com/datalayer-examples/jupyter-nextjs-example/issues/2
=> fix: Next.js example for SVG icon + Link to codesandbox example

docs/package.json, examples/docusaurus/package.json, packages/docusaurus-plugin/package.json
Fixes https://github.com/datalayer/jupyter-ui/issues/221
=> release: @datalayer/jupyter-docusaurus-plugin 0.1.0

dev/sh/start-jupyter-server.sh, docs/docs/deployments/jupyter-server/index.mdx, examples/cra/dev/sh/start-jupyter-server.sh, examples/docusaurus/README.md, examples/docusaurus/docs/intro.mdx, packages/docusaurus-plugin/README.md
=> fix: docusuarus server url

packages/react/src/components/jupyterlab/JupyterLabAppAdapter.ts, packages/react/src/components/jupyterlab/JupyterLabAppPlugins.ts, packages/react/webpack.config.js
Fixes https://github.com/datalayer/jupyter-ui/issues/235
=> chore: support disabled plugins - fixes #235

packages/react/src/components/codemirror/CodeMirrorEditor.tsx, packages/react/src/components/output/Output.tsx, packages/react/src/components/output/OutputState.ts, packages/react/src/examples/Cell.tsx, packages/react/src/examples/Output.tsx, packages/react/webpack.config.js
Fixes https://github.com/datalayer/jupyter-ui/issues/249
=> example: get outputs as json

examples/cra/src/examples/cell/CellComponents.tsx, examples/cra/src/examples/labapp/JupyterLabHeadlessApp.tsx, packages/react/package.json
This PR also remove the sharedPackages key for the jupyter-react jupyterlab extension.
=> fix: cra example

packages/react/src/components/cell/Cell.tsx, packages/react/src/components/cell/CellAdapter.ts, packages/react/src/components/cell/CellState.ts, packages/react/src/examples/All.tsx, packages/react/src/examples/Cell.tsx
Implements the support for multiple Cell state management - #255. 
Some issues to be confirmed will be documented here.
=> feat: add support for multiple Cell state management (#255)

packages/react/src/components/notebook/NotebookCommands.ts
Addresses issue where while using a notebook, you are unable to undo or redo a cut or paste option. Change should be tested as I am unable to run the react package locally.
=> Fix Undo Redo Stack

packages/react/src/examples/OutputWithMonitoring.tsx, packages/react/src/jupyter/kernel/KernelExecutor.ts, packages/react/src/jupyter/kernel/KernelState.ts, packages/react/webpack.config.js
Fix for https://github.com/datalayer/jupyter-ui/issues/314 
@echarles Please check this
=> 314, fixed assigning execution phase for stream output

packages/lexical/package.json, packages/react/src/jupyter/ipywidgets/libembed.ts
Add missing dependency react-json-tree
Fix typing error in libembed.ts
=> Minor fixes following build from scratch

packages/react/src/components/cell/Cell.tsx
Some solution #332 - for the main branch
=> Enabling custom kernels for Cell.tsx (#332) (main)

packages/react/src/components/notebook/cell/sidebar/CellSidebarExtension.tsx
fix: notebook's extensions prop doesn't work.
=> fix: customizable cell sidebar doesn't work.

packages/lexical/package.json, packages/lexical/src/editor/Editor.tsx, packages/lexical/src/examples/AppNbformat.tsx, packages/lexical/src/examples/AppSimple.tsx, packages/react/package.json
This PR also bumps versions for jupyter-react and jupyter-lexical
=> Lint: lexical example

docs/package.json, packages/react/src/components/notebook/Notebook.tsx, packages/react/src/examples/JupyterLabAppHeadless.tsx, packages/react/src/examples/JupyterLabAppHeadlessServerless.tsx, packages/react/src/examples/RunningSessions.tsx
=> Fix: jlab theme
